### PR TITLE
Fixing build on Linux

### PR DESCRIPTION
**Pull request by kkonrad**
Using `Dockerfile` instead of `dockerfile` fixes following error on Linux machines:
```
9 errors occurred:
	* unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/konrad/tech/opentelemetry-demo/timescaledb/Dockerfile: no such file or directory
	* unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/konrad/tech/opentelemetry-demo/special/Dockerfile: no such file or directory
	* unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/konrad/tech/opentelemetry-demo/upper/Dockerfile: no such file or directory
	* unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/konrad/tech/opentelemetry-demo/generator/Dockerfile: no such file or directory
	* unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/konrad/tech/opentelemetry-demo/lower/Dockerfile: no such file or directory
	* unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/konrad/tech/opentelemetry-demo/load/Dockerfile: no such file or directory
	* unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/konrad/tech/opentelemetry-demo/digit/Dockerfile: no such file or directory
	* unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/konrad/tech/opentelemetry-demo/collector/Dockerfile: no such file or directory
	* unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/konrad/tech/opentelemetry-demo/grafana/Dockerfile: no such file or directory
```

### CODE REVIEW

**Comment by jgpruitt** [comment]
@kkonrad hey! Thanks for the bug fix. I'd really like to merge it but we need you to sign our contributor license agreement first. Would you be willing to do that?

**Comment by kkonrad** [comment]
Hey, I'm still working on getting approval for this - please give me 2 more days. Sorry for this situation ...

**Comment by jgpruitt** [comment]
No problem, friend. Thanks for your contribution

**Comment by kkonrad** [comment]
It looks like for me getting approval to sign CLA will take so long that there is no point in keeping it open and potentially blocking others from fixing it. I'm really sorry for this situation

**Comment by jgpruitt** [comment]
@kkonrad I totally understand. No worries. Thanks for the bug report and the attempt at fixing it!

**Pull request closed without merging**
